# Generated by Django 3.2.13 on 2022-12-06 14:25

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/user_img/beemo.jpg', upload_to='images/'),
        ),
    ]
