# Generated by Django 3.2.13 on 2022-12-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
