# Generated by Django 3.2.13 on 2022-12-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='singer',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='song',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
