# Generated by Django 3.2.13 on 2022-12-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_like_likeitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likeitem',
            new_name='Likesong',
        ),
    ]
