# Generated by Django 3.2.13 on 2022-12-02 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_comment'),
        ('articles', '0008_rename_likeitem_likesong'),
    ]

    operations = [
    ]
