# Generated by Django 3.2.13 on 2022-12-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_song_maxresdefault'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_song',
            field=models.ManyToManyField(related_name='like_user', to='main.Song'),
        ),
    ]
