# Generated by Django 3.2.13 on 2022-12-06 14:31

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='images/user_img/default.jpg', null=True, upload_to='user_img/'),
        ),
    ]
