# Generated by Django 3.2.13 on 2022-12-06 14:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='user_img/default.png', null=True, upload_to='user_img/'),
        ),
    ]
