# Generated by Django 3.2.13 on 2022-12-12 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_like_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like_song',
        ),
    ]
