# Generated by Django 3.2.13 on 2022-12-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_last_name'),
        ('accounts', '0003_remove_user_like_song'),
    ]

    operations = [
    ]
