# Generated by Django 3.2.13 on 2022-12-07 04:47

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='https://i.esdrop.com/d/f/HV29DjMTCH/ls3BTlRkWF.png', null=True, upload_to='user_img/'),
        ),
    ]
