# Generated by Django 3.2.13 on 2022-12-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20221212_1447'),
        ('accounts', '0004_merge_20221212_1448'),
    ]

    operations = [
    ]
