# Generated by Django 3.2.13 on 2022-12-13 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20221213_0022'),
        ('accounts', '0005_merge_20221213_0732'),
    ]

    operations = [
    ]
