# Generated by Django 3.2.13 on 2022-12-09 02:28

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/'),
        ),
    ]
