# Generated by Django 3.2.13 on 2022-12-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="hqdefault",
            field=models.CharField(default=None, max_length=130, null=True),
        ),
    ]
