# Generated by Django 3.2.13 on 2022-12-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_song_maxresdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='maxresdefault',
            field=models.CharField(default=None, max_length=130, null=True),
        ),
    ]
