# Generated by Django 3.2.13 on 2022-12-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_song_maxresdefault'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='maxresdefault',
        ),
    ]
