# Generated by Django 3.2.13 on 2022-12-12 05:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_song_maxresdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like_users',
            field=models.ManyToManyField(related_name='like_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
