# Generated by Django 3.2.13 on 2022-12-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20221213_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='mqdefault_file',
        ),
        migrations.AlterField(
            model_name='song',
            name='default',
            field=models.CharField(default=None, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='hqdefault',
            field=models.CharField(default=None, max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='mqdefault',
            field=models.CharField(default=None, max_length=130, null=True),
        ),
    ]
